ecommerce_analytics:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'raw_data.db'
      schema: main
      schema_directory: 'target'
      schemas_and_paths:
        main: 'raw_data.db'
